version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  keycloak:
    image: jboss/keycloak:latest
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8180:8080
    depends_on:
      - postgres
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.admin
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 16543:80
    depends_on:
      - postgres
#  server:
#    build:
#      context: ./server
#      dockerfile: Dockerfile
#    container_name: server
#    restart: always
#    ports:
#      - 10080:3030
#    depends_on:
#      - postgres
#  camunda:
#    image: camunda/camunda-bpm-platform:latest
#    container_name: camunda
#    environment:
#      - DB_DRIVER=org.postgresql.Driver
#      - DB_URL=jdbc:postgresql://postgres:5432/camunda
#      - DB_USERNAME=camunda
#      - DB_PASSWORD=camunda
#      - WAIT_FOR=postgres:5432
#    ports:
#      - 8280:8080
#    depends_on:
#      - postgres
#    restart: unless-stopped

